<?php

namespace AppBundle\Repository;

/**
 * FourmisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FourmisRepository extends \Doctrine\ORM\EntityRepository
{
}
